debug: false
bootdo:
  uploadPath: D:/bootdo/
  mappingPath: /preview
  username: admin
  password: 123456
logging:
  level:
    root: info
    com.bootdo: warn
#    org.jasig.cas: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    username: root
    #自己本机访问地址
    #password: root
    #url: jdbc:mysql://127.0.0.1:3306/bootdo?useUnicode=true&characterEncoding=utf8
    #192.168.5.203数据库内网访问地址
#    url: jdbc:mysql://192.168.5.203:3306/bootdo?useUnicode=true&characterEncoding=utf8
#    password: Oking12345
    #正果正式服务器的地址
    url: jdbc:mysql://127.0.0.1:3306/bootdo?useUnicode=true&characterEncoding=utf8
    password: Oking#123
    #正果正式环境172.27.162.39上bootdo_test数据库
#    url: jdbc:mysql://172.27.162.39:3306/bootdo_test?useUnicode=true&characterEncoding=utf8
#    password: Oking#123
    #正果测试服务器的地址
#    url: jdbc:mysql://172.27.162.25:3306/bootdo?useUnicode=true&characterEncoding=utf8
#    password: oking123
    #192.168.5.203数据库外网访问地址
#    url: jdbc:mysql://183.237.175.100:33306/bootdo?useUnicode=true&characterEncoding=utf8
#    password: Oking12345
    initialSize: 600
    minIdle: 650
    maxActive: 1000
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    url2: jdbc:mysql://172.27.162.48:3306/baiyi_ylfw?useUnicode=true&characterEncoding=utf8
    username2: jaxi2
    password2: u0FxUft6e5UxD1AYEDsHFd95
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#        rabbitmq:
rabbitmq:
  bigDataCenterPush:
#    host: 127.0.0.1
    host: 172.27.162.38
    port: 5672
    virtualHost: /
    username: root
    password: oking
    automaticRecoveryEnabled: true
    networkRecoveryInterval: 3000
    exchangeName: big_data_center_event
    exchangeType: topic
    publisherReturns: true
    publisherConfirms: true
    specialPopulationSOS:
      queueName: specialPopulationSOS
      routingKey: event.specialPopulationSOS.*.*
sms:
  config:
    endpoint: http://172.27.11.105/dx/xfire/MsmService
    uid: sys_zhzg
    password: ZCsu6658794
    #是否开启短信
    open: true
    #屏蔽短信接收人员名单
    blockList: 钟海镇,赖辉
